image: node:22

pages:
  stage: deploy
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
  script:
    - pnpm install
    - pnpm build
  artifacts:
    paths:
      - dist
  rules: 
    - if: $CI_COMMIT_BRANCH == "main"
