name = "digi-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[vars]
CLOUDFLARE_ZONE_ID = "3647ed4e91b44f19f4c1dbcacfd8e028"
DOMAIN_NAME = "myanmardev.com"
FIREBASE_PROJECT_ID = "ting-51902"

# Sensitive vars — set via `wrangler secret put`
# CLOUDFLARE_API_TOKEN = ""
# FIREBASE_ADMIN_CLIENT_EMAIL = ""
# FIREBASE_ADMIN_PRIVATE_KEY = ""
